from ScraperRegistry import *
from NotesScraper import NotesScraper
from VideoLecturesScraper import VideoLecturesScraper

def initialize_scraper_registry():
    registry = ScraperRegistry()
    registry.register_scraper("Assignments", NotesScraper)
    registry.register_scraper("Lecture Notes", NotesScraper)
    registry.register_scraper("Video Lectures", VideoLecturesScraper)
    registry.register_scraper("Readings", NotesScraper)
    registry.register_scraper("Exams", NotesScraper)
    registry.register_scraper("Recitations", NotesScraper)
    registry.register_scraper("Study Materials", NotesScraper)
    registry.register_scraper("Recitation Videos", VideoLecturesScraper)
    registry.register_scraper("Recitation Notes", NotesScraper)
    registry.register_scraper("Lecture Notes & Slides", NotesScraper)
    registry.register_scraper("Case Studies", NotesScraper)
    registry.register_scraper("Class Videos", VideoLecturesScraper)
    registry.register_scraper("Class Session Videos", VideoLecturesScraper)
    registry.register_scraper("Episode", VideoLecturesScraper)
    registry.register_scraper("Videos for Advanced Lectures", VideoLecturesScraper)
    registry.register_scraper("Mega-Recitation Videos", VideoLecturesScraper)
    registry.register_scraper("Tutorials", NotesScraper)
    registry.register_scraper("Lecture Videos", VideoLecturesScraper)
    registry.register_scraper("Readings and Viewings", NotesScraper)
    registry.register_scraper("Final Projects", NotesScraper)
    registry.register_scraper("Exam Study Guides", NotesScraper)
    registry.register_scraper("Audio Lectures and Notes", VideoLecturesScraper)
    registry.register_scraper("Audio Lectures", VideoLecturesScraper)
    registry.register_scraper("Episodes", VideoLecturesScraper)
    registry.register_scraper("Video Discussions", VideoLecturesScraper)
    registry.register_scraper("Recitations", NotesScraper)
    registry.register_scraper("Course Materials", NotesScraper)
    registry.register_scraper("Lecture Slides", NotesScraper)
    registry.register_scraper("Projects", NotesScraper)
    registry.register_scraper("Quizzes", NotesScraper)
    registry.register_scraper("Labs", NotesScraper)
    registry.register_scraper("Presentations", NotesScraper)
    registry.register_scraper("Lecture Slides and Files", NotesScraper)
    registry.register_scraper("Calendar and Notes", NotesScraper)
    registry.register_scraper("Practice Problems", NotesScraper)
    registry.register_scraper("Resource Index", NotesScraper)
    registry.register_scraper("Videos", VideoLecturesScraper)
    registry.register_scraper("Lecture Slides and Code", NotesScraper)
    registry.register_scraper("Lecture Slides and Readings", NotesScraper)
    registry.register_scraper("Student Game Projects", NotesScraper)
    registry.register_scraper("Problem Sets", NotesScraper)
    registry.register_scraper("Lecture Notes & Handouts", NotesScraper)
    registry.register_scraper("Guest Video Lecture", VideoLecturesScraper)
    registry.register_scraper("Study Guides", NotesScraper)
    registry.register_scraper("Quizzes and Exams", NotesScraper)
    return registry